### ISSUE TITLE
The freecodecamp badge doesn't work

### ISSUE THREAD

**Issue by MarcelReig** [codemzy/codebadges#1]
Hello, do you know why the freecodecamp badge has stopped working?
Sorry if my english is not very good.
![captura de pantalla 2017-09-10 a las 14 40 46](https://user-images.githubusercontent.com/5702568/30249164-2163251e-9636-11e7-8777-83dc8705033f.png)

**Comment by codemzy** [comment]
Hi,

Thanks for letting me know. Looks like this was to do with a change to the freecodecamp url. I have updated the code, if you update to version 1.0.2 it should work again. 

```
<script src="https://cdn.jsdelivr.net/gh/codemzy/codebadges@1.0.2/dist/codebadges.min.js"></script>
```

**Comment by MarcelReig** [comment]
Hi,
Thanks, yes it work again!
